#!/bin/bash
#
# railsapp

# chkconfig: 2345 82 55
# processname: railsapp
# description: Runs railsapp for nginx integration.

# Include RedHat function library
. /etc/rc.d/init.d/functions

# The name of the service
NAME=railsapp

# The username and path to the myapp source
USER=bondgate
APP_PATH=__APP_FULL_PATH__
APP_ROOT="$APP_PATH/current"

# The PID and LOCK files used by puma and sidekiq
UPID=$APP_ROOT/tmp/pids/puma.pid
ULOCK=/var/lock/subsys/$NAME

# The options to use when running puma
#OPTS="-F $APP_ROOT/config/puma.rb"

# Ruby related path update
# RUBY_PATH_PATCH="PATH=$PATH:/usr/local/bin:/usr/local/lib && export PATH && "
# BUNDLE_CMD=bundle
# PUMA_CMD=pumactl
# . /etc/profile.d/rbenv.sh

RBENV_RUBY_VERSION=`cat $APP_ROOT/.ruby-version`
RBENV_ROOT="/home/$USER/.rbenv"
PATH="$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH"
SET_PATH="cd $APP_ROOT; rbenv rehash; rbenv local $RBENV_RUBY_VERSION"
DAEMON="RAILS_ENV=production bundle exec puma"
DAEMON_OPTS="-C $APP_ROOT/config/puma.conf.rb --daemon"
CMD="$SET_PATH; $DAEMON $DAEMON_OPTS"

start() {
  cd $APP_PATH
  # Start puma
  echo -n $"Starting $NAME: "
  su - $USER -c "$CMD"
  puma=$?
  [ $puma -eq 0 ] && touch $ULOCK
  echo

  return $puma
}

stop() {
  cd $APP_PATH

  # Stop puma
  echo -n $"Stopping $NAME: "
  killproc -p $UPID
  puma=$?
  [ $puma -eq 0 ] && rm -f $ULOCK
  echo

  return $puma
}

restart() {
  stop
  start
}

get_status() {
  status -p $UPID $NAME
}

query_status() {
  get_status >/dev/null 2>&1
}

case "$1" in
  start)
    query_status && exit 0
    start
    ;;
  stop)
    query_status || exit 0
    stop
    ;;
  restart)
    restart
    ;;
  status)
    get_status
    exit $?
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0